---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
  namespace: frontend
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - pods
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - patch  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: frontend
roleRef:
  apiGroup: ""
  kind: Role
  name: deployment-role
subjects:
  - kind: User
    name: developerbob
    apiGroup: ""
---
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::719217631821:role/eksctl-eks-access-test-nodegroup-NodeInstanceRole-1U4X1KCH9BEMJ
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    # - userarn: arn:aws:iam::719217631821:user/NoPerm
    #   username: anyname
    #   groups:
    #     - system:masters
    - userarn: arn:aws:iam::719217631821:user/bob 
      username: developerbob
      groups:
        - deployment-role
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-01T18:56:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "23737"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9b0d3aef-efe6-4325-bb59-5c64ea5bff24
